FROM httpd:2.4
MAINTAINER DIEGO diegodir92@educastur.es
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
RUN apt-get clear
EXPOSE 80
COPY weblotr /usr/local/apache2/htdocs
CMD ["apache2ctl", "-D", "FOREGROUND"]